name: Build and Deploy FastAPI App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (optional, for validation)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests
      # - name: Run Tests
      #   run: pytest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'et-ci-dev-vai-api'  # 👈 Your Azure App Service name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_39D4E108497845808D1916F2DD20D1A4 }}
          package: .
